import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"
import Footer from "./Components/Footer";
import Navbar2 from "./Components/Navbar2";
import NavBar from "./Components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

    
    {children}
    
  </body>
</html>
  );
}
